# Configuration Preset used on Omu Magpie.

[game]
# Hub Information
hostname = "[MRP] Omu Magpie ᴺᴬ⁻ᴱ"
desc = "Come join us on Omu Station! A roleplay-centric game focus with the added chaos of Goob antags and more!"

# Player Controls
soft_max_players = 50
