# Configuration preset used on Omu Woodpecker.

[game]
# Hub Information
hostname = "[MRP] Omu Woodpecker ᴺᴬ⁻ᴱ"
desc = "Come join us on Omu Station! A roleplay-centric game focus with the added chaos of Goob antags and more!"
